const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  // But you can create a sidebar manually
  computerSidebar: [{ type: 'autogenerated', dirName: 'computer' }],
  developSidebar: [{ type: 'autogenerated', dirName: 'development' }],
  toolsSidebar: [{ type: 'autogenerated', dirName: 'tools' }],
};

module.exports = sidebars;
