const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  // But you can create a sidebar manually
  computerSidebar: [{ type: 'autogenerated', dirName: 'computer' }],
};

module.exports = sidebars;
